name: Publish to NuGet

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          2.1.x
          3.1.x
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
      
    - name: Restore packages
      run: nuget restore ../Wapi2.SDK.sln
      working-directory: Wapi2.SDK
      
    - name: Build solution
      run: |
        msbuild ../Wapi2.SDK.sln /p:Configuration=Release /p:Platform="Any CPU"
      working-directory: Wapi2.SDK
        
    - name: Create NuGet package
      run: |
        msbuild /t:pack /p:Configuration=Release /p:PackageOutputPath=./nupkgs
      working-directory: Wapi2.SDK
        
    - name: Push to NuGet
      run: |
        dotnet nuget push "./nupkgs/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: Wapi2.SDK